var hierarchy =
[
    [ "FLootLockerServerAlterPlayerInventoryRequestBase", "structFLootLockerServerAlterPlayerInventoryRequestBase.html", [
      [ "FLootLockerServerAlterPlayerInventoryByAssetIdAndAssetVariationIdRequest", "structFLootLockerServerAlterPlayerInventoryByAssetIdAndAssetVariationIdRequest.html", null ],
      [ "FLootLockerServerAlterPlayerInventoryByAssetIdAndRentalOptionIdRequest", "structFLootLockerServerAlterPlayerInventoryByAssetIdAndRentalOptionIdRequest.html", null ],
      [ "FLootLockerServerAlterPlayerInventoryByAssetIdRequest", "structFLootLockerServerAlterPlayerInventoryByAssetIdRequest.html", null ]
    ] ],
    [ "FLootLockerServerAssetByAssetIdAndRentalOptionIdRequest", "structFLootLockerServerAssetByAssetIdAndRentalOptionIdRequest.html", null ],
    [ "FLootLockerServerAssetByAssetIdAndVariationIdRequest", "structFLootLockerServerAssetByAssetIdAndVariationIdRequest.html", null ],
    [ "FLootLockerServerAssetByAssetIdRequest", "structFLootLockerServerAssetByAssetIdRequest.html", null ],
    [ "FLootLockerServerAssetByAssetInstanceIdRequest", "structFLootLockerServerAssetByAssetInstanceIdRequest.html", null ],
    [ "FLootLockerServerAssetByInstanceIDRequest", "structFLootLockerServerAssetByInstanceIDRequest.html", null ],
    [ "FLootLockerServerAssetCandidateInformation", "structFLootLockerServerAssetCandidateInformation.html", null ],
    [ "FLootLockerServerAssetFile", "structFLootLockerServerAssetFile.html", null ],
    [ "FLootLockerServerAssetHeroEquipException", "structFLootLockerServerAssetHeroEquipException.html", null ],
    [ "FLootLockerServerAssetInstanceStorageKeyValueSet", "structFLootLockerServerAssetInstanceStorageKeyValueSet.html", null ],
    [ "FLootLockerServerAssetRarity", "structFLootLockerServerAssetRarity.html", null ],
    [ "FLootLockerServerAssetRentalOption", "structFLootLockerServerAssetRentalOption.html", null ],
    [ "FLootLockerServerAssetReward", "structFLootLockerServerAssetReward.html", null ],
    [ "FLootLockerServerAssetRewardDetails", "structFLootLockerServerAssetRewardDetails.html", null ],
    [ "FLootLockerServerAssetStorageKeyValueSet", "structFLootLockerServerAssetStorageKeyValueSet.html", null ],
    [ "FLootLockerServerAssetVariation", "structFLootLockerServerAssetVariation.html", null ],
    [ "FLootLockerServerAssetVariationProperty", "structFLootLockerServerAssetVariationProperty.html", null ],
    [ "FLootLockerServerAssetWithoutPackageContent", "structFLootLockerServerAssetWithoutPackageContent.html", [
      [ "FLootLockerServerAsset", "structFLootLockerServerAsset.html", [
        [ "FLootLockerServerTriggeredAsset", "structFLootLockerServerTriggeredAsset.html", null ]
      ] ]
    ] ],
    [ "FLootLockerServerAuthenticationRequest", "structFLootLockerServerAuthenticationRequest.html", null ],
    [ "FLootLockerServerBalance", "structFLootLockerServerBalance.html", null ],
    [ "FLootLockerServerBalanceModifiers", "structFLootLockerServerBalanceModifiers.html", null ],
    [ "FLootLockerServerBalanceWithCurrencyId", "structFLootLockerServerBalanceWithCurrencyId.html", null ],
    [ "FLootLockerServerCharacterProgression", "structFLootLockerServerCharacterProgression.html", null ],
    [ "FLootLockerServerConnectedAccount", "structFLootLockerServerConnectedAccount.html", null ],
    [ "FLootLockerServerContext", "structFLootLockerServerContext.html", null ],
    [ "FLootLockerServerCreateAssetInstanceKeyValuePairRequest", "structFLootLockerServerCreateAssetInstanceKeyValuePairRequest.html", null ],
    [ "FLootLockerServerCreateLeaderboardScheduleRequest", "structFLootLockerServerCreateLeaderboardScheduleRequest.html", null ],
    [ "FLootLockerServerCreatePlayerRequest", "structFLootLockerServerCreatePlayerRequest.html", null ],
    [ "FLootLockerServerCreateWalletRequest", "structFLootLockerServerCreateWalletRequest.html", null ],
    [ "FLootLockerServerCreditRequest", "structFLootLockerServerCreditRequest.html", null ],
    [ "FLootLockerServerCurrency", "structFLootLockerServerCurrency.html", null ],
    [ "FLootLockerServerCurrencyReward", "structFLootLockerServerCurrencyReward.html", null ],
    [ "FLootLockerServerCurrencyRewardDetails", "structFLootLockerServerCurrencyRewardDetails.html", null ],
    [ "FLootLockerServerDebitRequest", "structFLootLockerServerDebitRequest.html", null ],
    [ "FLootLockerServerDropTableItem", "structFLootLockerServerDropTableItem.html", null ],
    [ "FLootLockerServerEmptyRequest", "structFLootLockerServerEmptyRequest.html", null ],
    [ "FLootLockerServerEquipAssetToCharacterLoadoutByAssetIdAndRentalOptionIdRequest", "structFLootLockerServerEquipAssetToCharacterLoadoutByAssetIdAndRentalOptionIdRequest.html", null ],
    [ "FLootLockerServerEquipAssetToCharacterLoadoutByAssetIdAndVariationIdRequest", "structFLootLockerServerEquipAssetToCharacterLoadoutByAssetIdAndVariationIdRequest.html", null ],
    [ "FLootLockerServerEquipAssetToCharacterLoadoutRequest", "structFLootLockerServerEquipAssetToCharacterLoadoutRequest.html", null ],
    [ "FLootLockerServerEquipAssetToHeroLoadoutByAssetIdAndRentalOptionIdRequest", "structFLootLockerServerEquipAssetToHeroLoadoutByAssetIdAndRentalOptionIdRequest.html", null ],
    [ "FLootLockerServerEquipAssetToHeroLoadoutByAssetIdAndVariationIdRequest", "structFLootLockerServerEquipAssetToHeroLoadoutByAssetIdAndVariationIdRequest.html", null ],
    [ "FLootLockerServerEquipAssetToHeroLoadoutRequest", "structFLootLockerServerEquipAssetToHeroLoadoutRequest.html", null ],
    [ "FLootLockerServerErrorData", "structFLootLockerServerErrorData.html", null ],
    [ "FLootLockerServerExtendedIndexBasedPagination", "structFLootLockerServerExtendedIndexBasedPagination.html", null ],
    [ "FLootLockerServerExtendedPaginationError", "structFLootLockerServerExtendedPaginationError.html", null ],
    [ "FLootLockerServerFriend", "structFLootLockerServerFriend.html", null ],
    [ "FLootLockerServerGameProgression", "structFLootLockerServerGameProgression.html", null ],
    [ "FLootLockerServerGetMultisourceMetadataRequest", "structFLootLockerServerGetMultisourceMetadataRequest.html", null ],
    [ "FLootLockerServerGetPlayerInfoFromGameSessionTokenRequest", "structFLootLockerServerGetPlayerInfoFromGameSessionTokenRequest.html", null ],
    [ "FLootLockerServerIndexBasedPagination", "structFLootLockerServerIndexBasedPagination.html", null ],
    [ "FLootLockerServerInstanceProgression", "structFLootLockerServerInstanceProgression.html", null ],
    [ "FLootLockerServerInvokeTriggerForPlayerRequest", "structFLootLockerServerInvokeTriggerForPlayerRequest.html", null ],
    [ "FLootLockerServerKeyBasedPagination", "structFLootLockerServerKeyBasedPagination.html", null ],
    [ "FLootLockerServerLeaderboard", "structFLootLockerServerLeaderboard.html", null ],
    [ "FLootLockerServerLeaderboardArchive", "structFLootLockerServerLeaderboardArchive.html", null ],
    [ "FLootLockerServerLeaderboardArchiveDetails", "structFLootLockerServerLeaderboardArchiveDetails.html", null ],
    [ "FLootLockerServerLeaderboardArchivePlayer", "structFLootLockerServerLeaderboardArchivePlayer.html", null ],
    [ "FLootLockerServerLeaderboardAssetReward", "structFLootLockerServerLeaderboardAssetReward.html", null ],
    [ "FLootLockerServerLeaderboardBaseRequest", "structFLootLockerServerLeaderboardBaseRequest.html", [
      [ "FLootLockerServerCreateLeaderboardRequest", "structFLootLockerServerCreateLeaderboardRequest.html", null ],
      [ "FLootLockerServerUpdateLeaderboardRequest", "structFLootLockerServerUpdateLeaderboardRequest.html", null ]
    ] ],
    [ "FLootLockerServerLeaderboardCurrencyReward", "structFLootLockerServerLeaderboardCurrencyReward.html", null ],
    [ "FLootLockerServerLeaderboardDetailPredicates", "structFLootLockerServerLeaderboardDetailPredicates.html", null ],
    [ "FLootLockerServerLeaderboardEntry", "structFLootLockerServerLeaderboardEntry.html", null ],
    [ "FLootLockerServerLeaderboardEntryWithLeaderboardData", "structFLootLockerServerLeaderboardEntryWithLeaderboardData.html", null ],
    [ "FLootLockerServerLeaderboardGroupReward", "structFLootLockerServerLeaderboardGroupReward.html", null ],
    [ "FLootLockerServerLeaderboardGroupRewardAssociation", "structFLootLockerServerLeaderboardGroupRewardAssociation.html", null ],
    [ "FLootLockerServerLeaderboardGroupRewardMetadata", "structFLootLockerServerLeaderboardGroupRewardMetadata.html", null ],
    [ "FLootLockerServerLeaderboardIncrementScoreRequest", "structFLootLockerServerLeaderboardIncrementScoreRequest.html", null ],
    [ "FLootLockerServerLeaderboardPlayer", "structFLootLockerServerLeaderboardPlayer.html", null ],
    [ "FLootLockerServerLeaderboardProgressionPointsReward", "structFLootLockerServerLeaderboardProgressionPointsReward.html", null ],
    [ "FLootLockerServerLeaderboardProgressionResetReward", "structFLootLockerServerLeaderboardProgressionResetReward.html", null ],
    [ "FLootLockerServerLeaderboardReward", "structFLootLockerServerLeaderboardReward.html", null ],
    [ "FLootLockerServerLeaderboardRewardArgs", "structFLootLockerServerLeaderboardRewardArgs.html", null ],
    [ "FLootLockerServerLeaderboardSchedule", "structFLootLockerServerLeaderboardSchedule.html", null ],
    [ "FLootLockerServerLeaderboardSubmitScoreRequest", "structFLootLockerServerLeaderboardSubmitScoreRequest.html", null ],
    [ "FLootLockerServerListAssetsRequest", "structFLootLockerServerListAssetsRequest.html", null ],
    [ "FLootLockerServerListConnectedAccountsRequest", "structFLootLockerServerListConnectedAccountsRequest.html", null ],
    [ "FLootLockerServerMetadataBase64Value", "structFLootLockerServerMetadataBase64Value.html", null ],
    [ "FLootLockerServerMetadataEntry", "structFLootLockerServerMetadataEntry.html", null ],
    [ "FLootLockerServerMetadataSourceAndEntries", "structFLootLockerServerMetadataSourceAndEntries.html", null ],
    [ "FLootLockerServerMetadataSourceAndKeys", "structFLootLockerServerMetadataSourceAndKeys.html", null ],
    [ "FLootLockerServerModifyScoreRequest", "structFLootLockerServerModifyScoreRequest.html", null ],
    [ "FLootLockerServerNotificationNoContentObject", "structFLootLockerServerNotificationNoContentObject.html", null ],
    [ "FLootLockerServerNotificationProperty", "structFLootLockerServerNotificationProperty.html", null ],
    [ "FLootLockerServerPackageContentItem", "structFLootLockerServerPackageContentItem.html", null ],
    [ "FLootLockerServerPickDropsFromDropTableRequest", "structFLootLockerServerPickDropsFromDropTableRequest.html", null ],
    [ "FLootLockerServerPickedDropTableItem", "structFLootLockerServerPickedDropTableItem.html", null ],
    [ "FLootLockerServerPlayerCharacter", "structFLootLockerServerPlayerCharacter.html", null ],
    [ "FLootLockerServerPlayerCharacterInventoryItem", "structFLootLockerServerPlayerCharacterInventoryItem.html", null ],
    [ "FLootLockerServerPlayerCharacterItemRentalData", "structFLootLockerServerPlayerCharacterItemRentalData.html", null ],
    [ "FLootLockerServerPlayerCharacterLoadoutItem", "structFLootLockerServerPlayerCharacterLoadoutItem.html", null ],
    [ "FLootLockerServerPlayerFile", "structFLootLockerServerPlayerFile.html", null ],
    [ "FLootLockerServerPlayerHero", "structFLootLockerServerPlayerHero.html", null ],
    [ "FLootLockerServerPlayerHeroInventoryItem", "structFLootLockerServerPlayerHeroInventoryItem.html", null ],
    [ "FLootLockerServerPlayerHeroItemRentalData", "structFLootLockerServerPlayerHeroItemRentalData.html", null ],
    [ "FLootLockerServerPlayerHeroLoadoutItem", "structFLootLockerServerPlayerHeroLoadoutItem.html", null ],
    [ "FLootLockerServerPlayerInfoFromToken", "structFLootLockerServerPlayerInfoFromToken.html", null ],
    [ "FLootLockerServerPlayerInventoryItem", "structFLootLockerServerPlayerInventoryItem.html", null ],
    [ "FLootLockerServerPlayerItemRentalData", "structFLootLockerServerPlayerItemRentalData.html", null ],
    [ "FLootLockerServerPlayerLoadoutItem", "structFLootLockerServerPlayerLoadoutItem.html", null ],
    [ "FLootLockerServerPlayerName", "structFLootLockerServerPlayerName.html", null ],
    [ "FLootLockerServerPlayerNameLookupPair", "structFLootLockerServerPlayerNameLookupPair.html", null ],
    [ "FLootLockerServerPlayerPersistentStorageEntry_NamedItems", "structFLootLockerServerPlayerPersistentStorageEntry__NamedItems.html", null ],
    [ "FLootLockerServerPlayerPersistentStorageEntry_NamedSets", "structFLootLockerServerPlayerPersistentStorageEntry__NamedSets.html", null ],
    [ "FLootLockerServerPlayerPersistentStorageEntry_NamedStorage", "structFLootLockerServerPlayerPersistentStorageEntry__NamedStorage.html", null ],
    [ "FLootLockerServerPlayerPersistentStorageGetPublicStorageForPlayersAndKeysRequest", "structFLootLockerServerPlayerPersistentStorageGetPublicStorageForPlayersAndKeysRequest.html", null ],
    [ "FLootLockerServerPlayerPersistentStorageKeyValueSet", "structFLootLockerServerPlayerPersistentStorageKeyValueSet.html", [
      [ "FLootLockerServerPlayerPersistentStorageKeyValueSetWithOrder", "structFLootLockerServerPlayerPersistentStorageKeyValueSetWithOrder.html", null ]
    ] ],
    [ "FLootLockerServerPlayerPersistentStorageUpdateEntryOrdered", "structFLootLockerServerPlayerPersistentStorageUpdateEntryOrdered.html", null ],
    [ "FLootLockerServerPlayerPersistentStorageUpdateRequest", "structFLootLockerServerPlayerPersistentStorageUpdateRequest.html", null ],
    [ "FLootLockerServerPlayerPlatform", "structFLootLockerServerPlayerPlatform.html", null ],
    [ "FLootLockerServerPlayerProgression", "structFLootLockerServerPlayerProgression.html", null ],
    [ "FLootLockerServerProgressionPointRewardDetails", "structFLootLockerServerProgressionPointRewardDetails.html", null ],
    [ "FLootLockerServerProgressionPointsReward", "structFLootLockerServerProgressionPointsReward.html", null ],
    [ "FLootLockerServerProgressionResetReward", "structFLootLockerServerProgressionResetReward.html", null ],
    [ "FLootLockerServerProgressionResetRewardDetails", "structFLootLockerServerProgressionResetRewardDetails.html", null ],
    [ "FLootLockerServerProgressionTier", "structFLootLockerServerProgressionTier.html", null ],
    [ "FLootLockerServerRequestContext", "structFLootLockerServerRequestContext.html", null ],
    [ "FLootLockerServerResponse", "structFLootLockerServerResponse.html", [
      [ "FLootLockerServerAddAssetToPlayerInventoryResponse", "structFLootLockerServerAddAssetToPlayerInventoryResponse.html", null ],
      [ "FLootLockerServerAlterPlayerInventoryResponse", "structFLootLockerServerAlterPlayerInventoryResponse.html", null ],
      [ "FLootLockerServerAssetInstanceKeyValuePairItemResponse", "structFLootLockerServerAssetInstanceKeyValuePairItemResponse.html", null ],
      [ "FLootLockerServerAssetInstanceKeyValuePairsListResponse", "structFLootLockerServerAssetInstanceKeyValuePairsListResponse.html", null ],
      [ "FLootLockerServerAuthenticationResponse", "structFLootLockerServerAuthenticationResponse.html", null ],
      [ "FLootLockerServerCharacterProgressionListResponse", "structFLootLockerServerCharacterProgressionListResponse.html", null ],
      [ "FLootLockerServerComputeAndLockDropTableResponse", "structFLootLockerServerComputeAndLockDropTableResponse.html", null ],
      [ "FLootLockerServerCreatePlayerResponse", "structFLootLockerServerCreatePlayerResponse.html", null ],
      [ "FLootLockerServerCreateWalletResponse", "structFLootLockerServerCreateWalletResponse.html", null ],
      [ "FLootLockerServerCreditWalletResponse", "structFLootLockerServerCreditWalletResponse.html", null ],
      [ "FLootLockerServerDebitWalletResponse", "structFLootLockerServerDebitWalletResponse.html", null ],
      [ "FLootLockerServerDeletePersistentStorageForPlayersAndKeysResponse", "structFLootLockerServerDeletePersistentStorageForPlayersAndKeysResponse.html", null ],
      [ "FLootLockerServerFullCharacterLoadoutResponse", "structFLootLockerServerFullCharacterLoadoutResponse.html", [
        [ "FLootLockerServerEquipAssetToCharacterLoadoutResponse", "structFLootLockerServerEquipAssetToCharacterLoadoutResponse.html", null ],
        [ "FLootLockerServerGetCharacterLoadoutResponse", "structFLootLockerServerGetCharacterLoadoutResponse.html", null ],
        [ "FLootLockerServerUnequipAssetFromCharacterLoadoutResponse", "structFLootLockerServerUnequipAssetFromCharacterLoadoutResponse.html", null ]
      ] ],
      [ "FLootLockerServerFullHeroLoadoutResponse", "structFLootLockerServerFullHeroLoadoutResponse.html", [
        [ "FLootLockerServerEquipAssetToHeroLoadoutResponse", "structFLootLockerServerEquipAssetToHeroLoadoutResponse.html", null ],
        [ "FLootLockerServerGetHeroLoadoutResponse", "structFLootLockerServerGetHeroLoadoutResponse.html", null ],
        [ "FLootLockerServerUnequipAssetFromHeroLoadoutResponse", "structFLootLockerServerUnequipAssetFromHeroLoadoutResponse.html", null ]
      ] ],
      [ "FLootLockerServerFullPlayerLoadoutResponse", "structFLootLockerServerFullPlayerLoadoutResponse.html", [
        [ "FLootLockerServerEquipAssetToPlayerLoadoutResponse", "structFLootLockerServerEquipAssetToPlayerLoadoutResponse.html", null ],
        [ "FLootLockerServerGetPlayerLoadoutResponse", "structFLootLockerServerGetPlayerLoadoutResponse.html", null ],
        [ "FLootLockerServerUnequipAssetFromPlayerLoadoutResponse", "structFLootLockerServerUnequipAssetFromPlayerLoadoutResponse.html", null ]
      ] ],
      [ "FLootLockerServerGameProgressionListResponse", "structFLootLockerServerGameProgressionListResponse.html", null ],
      [ "FLootLockerServerGetAllMemberRanksResponse", "structFLootLockerServerGetAllMemberRanksResponse.html", null ],
      [ "FLootLockerServerGetAssetsResponse", "structFLootLockerServerGetAssetsResponse.html", null ],
      [ "FLootLockerServerGetCharacterInventoryResponse", "structFLootLockerServerGetCharacterInventoryResponse.html", null ],
      [ "FLootLockerServerGetHeroInventoryResponse", "structFLootLockerServerGetHeroInventoryResponse.html", null ],
      [ "FLootLockerServerGetLeaderboardResponse", "structFLootLockerServerGetLeaderboardResponse.html", null ],
      [ "FLootLockerServerGetLeaderboardScheduleResponse", "structFLootLockerServerGetLeaderboardScheduleResponse.html", null ],
      [ "FLootLockerServerGetMetadataResponse", "structFLootLockerServerGetMetadataResponse.html", null ],
      [ "FLootLockerServerGetMultisourceMetadataResponse", "structFLootLockerServerGetMultisourceMetadataResponse.html", null ],
      [ "FLootLockerServerGetPersistentStorageForPlayersResponse", "structFLootLockerServerGetPersistentStorageForPlayersResponse.html", null ],
      [ "FLootLockerServerGetPlayerCharactersResponse", "structFLootLockerServerGetPlayerCharactersResponse.html", null ],
      [ "FLootLockerServerGetPlayerHeroesResponse", "structFLootLockerServerGetPlayerHeroesResponse.html", null ],
      [ "FLootLockerServerGetPlayerInfoFromGameSessionTokenResponse", "structFLootLockerServerGetPlayerInfoFromGameSessionTokenResponse.html", null ],
      [ "FLootLockerServerGetPlayerInventoryResponse", "structFLootLockerServerGetPlayerInventoryResponse.html", null ],
      [ "FLootLockerServerGetPublicPersistentStorageForPlayersAndKeysResponse", "structFLootLockerServerGetPublicPersistentStorageForPlayersAndKeysResponse.html", null ],
      [ "FLootLockerServerGetScoresFromLeaderboardResponse", "structFLootLockerServerGetScoresFromLeaderboardResponse.html", null ],
      [ "FLootLockerServerGetUniversalInventoryResponse", "structFLootLockerServerGetUniversalInventoryResponse.html", null ],
      [ "FLootLockerServerGetWalletResponse", "structFLootLockerServerGetWalletResponse.html", null ],
      [ "FLootLockerServerInstanceProgressionListResponse", "structFLootLockerServerInstanceProgressionListResponse.html", null ],
      [ "FLootLockerServerInvokeTriggerResponse", "structFLootLockerServerInvokeTriggerResponse.html", null ],
      [ "FLootLockerServerLeaderboardArchiveDetailsResponse", "structFLootLockerServerLeaderboardArchiveDetailsResponse.html", null ],
      [ "FLootLockerServerLeaderboardArchiveResponse", "structFLootLockerServerLeaderboardArchiveResponse.html", null ],
      [ "FLootLockerServerLeaderboardBaseResponse", "structFLootLockerServerLeaderboardBaseResponse.html", [
        [ "FLootLockerServerCreateLeaderboardResponse", "structFLootLockerServerCreateLeaderboardResponse.html", null ],
        [ "FLootLockerServerUpdateLeaderboardResponse", "structFLootLockerServerUpdateLeaderboardResponse.html", null ]
      ] ],
      [ "FLootLockerServerLeaderboardSubmitScoreResponse", "structFLootLockerServerLeaderboardSubmitScoreResponse.html", null ],
      [ "FLootLockerServerListAssetsResponse", "structFLootLockerServerListAssetsResponse.html", null ],
      [ "FLootLockerServerListBalancesForWalletResponse", "structFLootLockerServerListBalancesForWalletResponse.html", null ],
      [ "FLootLockerServerListConnectedAccountsResponse", "structFLootLockerServerListConnectedAccountsResponse.html", null ],
      [ "FLootLockerServerListContextsResponse", "structFLootLockerServerListContextsResponse.html", null ],
      [ "FLootLockerServerListCurrenciesResponse", "structFLootLockerServerListCurrenciesResponse.html", null ],
      [ "FLootLockerServerListFriendsResponse", "structFLootLockerServerListFriendsResponse.html", null ],
      [ "FLootLockerServerListLeaderboardsResponse", "structFLootLockerServerListLeaderboardsResponse.html", null ],
      [ "FLootLockerServerListMetadataResponse", "structFLootLockerServerListMetadataResponse.html", null ],
      [ "FLootLockerServerMaintainSessionResponse", "structFLootLockerServerMaintainSessionResponse.html", null ],
      [ "FLootLockerServerPickFromDropTableResponse", "structFLootLockerServerPickFromDropTableResponse.html", null ],
      [ "FLootLockerServerPlayerFileDeleteResponse", "structFLootLockerServerPlayerFileDeleteResponse.html", null ],
      [ "FLootLockerServerPlayerFileListResponse", "structFLootLockerServerPlayerFileListResponse.html", null ],
      [ "FLootLockerServerPlayerNameLookupResponse", "structFLootLockerServerPlayerNameLookupResponse.html", null ],
      [ "FLootLockerServerPlayerProgressionListResponse", "structFLootLockerServerPlayerProgressionListResponse.html", null ],
      [ "FLootLockerServerProgressionTiersResponse", "structFLootLockerServerProgressionTiersResponse.html", null ],
      [ "FLootLockerServerSendNotificationsResponse", "structFLootLockerServerSendNotificationsResponse.html", null ],
      [ "FLootLockerServerSetMetadataResponse", "structFLootLockerServerSetMetadataResponse.html", null ],
      [ "FLootLockerServerSingleCharacterProgressionResponse", "structFLootLockerServerSingleCharacterProgressionResponse.html", [
        [ "FLootLockerServerSingleCharacterProgressionWithRewardsResponse", "structFLootLockerServerSingleCharacterProgressionWithRewardsResponse.html", null ]
      ] ],
      [ "FLootLockerServerSingleGameProgressionResponse", "structFLootLockerServerSingleGameProgressionResponse.html", null ],
      [ "FLootLockerServerSingleInstanceProgressionResponse", "structFLootLockerServerSingleInstanceProgressionResponse.html", [
        [ "FLootLockerServerSingleInstanceProgressionWithRewardsResponse", "structFLootLockerServerSingleInstanceProgressionWithRewardsResponse.html", null ]
      ] ],
      [ "FLootLockerServerSinglePlayerFileResponse", "structFLootLockerServerSinglePlayerFileResponse.html", null ],
      [ "FLootLockerServerSinglePlayerProgressionResponse", "structFLootLockerServerSinglePlayerProgressionResponse.html", [
        [ "FLootLockerServerSinglePlayerProgressionWithRewardsResponse", "structFLootLockerServerSinglePlayerProgressionWithRewardsResponse.html", null ]
      ] ],
      [ "FLootLockerServerTokenExchangeResponse", "structFLootLockerServerTokenExchangeResponse.html", null ],
      [ "FLootLockerServerUpdatePersistentStorageForPlayersAndKeysResponse", "structFLootLockerServerUpdatePersistentStorageForPlayersAndKeysResponse.html", null ]
    ] ],
    [ "FLootLockerServerRewards", "structFLootLockerServerRewards.html", null ],
    [ "FLootLockerServerSendNotificationsToPlayerBaseRequest", "structFLootLockerServerSendNotificationsToPlayerBaseRequest.html", null ],
    [ "FLootLockerServerSetMetadataAction", "structFLootLockerServerSetMetadataAction.html", null ],
    [ "FLootLockerServerSetMetadataError", "structFLootLockerServerSetMetadataError.html", null ],
    [ "FLootLockerServerSetMetadataErrorEntry", "structFLootLockerServerSetMetadataErrorEntry.html", null ],
    [ "FLootLockerServerSimpleAsset", "structFLootLockerServerSimpleAsset.html", null ],
    [ "FLootLockerServerSimpleAssetAuthor", "structFLootLockerServerSimpleAssetAuthor.html", null ],
    [ "FLootLockerServerSimpleAssetDataEntity", "structFLootLockerServerSimpleAssetDataEntity.html", null ],
    [ "FLootLockerServerSimpleAssetExcludes", "structFLootLockerServerSimpleAssetExcludes.html", null ],
    [ "FLootLockerServerSimpleAssetFile", "structFLootLockerServerSimpleAssetFile.html", null ],
    [ "FLootLockerServerSimpleAssetFilters", "structFLootLockerServerSimpleAssetFilters.html", null ],
    [ "FLootLockerServerSimpleAssetIncludes", "structFLootLockerServerSimpleAssetIncludes.html", null ],
    [ "FLootLockerServerTriggeredLevel", "structFLootLockerServerTriggeredLevel.html", null ],
    [ "FLootLockerServerTriggeredXP", "structFLootLockerServerTriggeredXP.html", null ],
    [ "FLootLockerServerUniversalInventoryItem", "structFLootLockerServerUniversalInventoryItem.html", null ],
    [ "FLootLockerServerUpdateOneOrMoreKeyValuePairsOnAssetInstanceRequest", "structFLootLockerServerUpdateOneOrMoreKeyValuePairsOnAssetInstanceRequest.html", null ],
    [ "LootLockerServerResponseFactory", "classLootLockerServerResponseFactory.html", null ],
    [ "LootLockerServerStaticRequestErrorStatusCodes", "structLootLockerServerStaticRequestErrorStatusCodes.html", null ],
    [ "UObject", null, [
      [ "ULootLockerServerAssetRequest", "classULootLockerServerAssetRequest.html", null ],
      [ "ULootLockerServerAuthRequest", "classULootLockerServerAuthRequest.html", null ],
      [ "ULootLockerServerBalanceRequest", "classULootLockerServerBalanceRequest.html", null ],
      [ "ULootLockerServerCharacterProgressionRequest", "classULootLockerServerCharacterProgressionRequest.html", null ],
      [ "ULootLockerServerCharacterRequest", "classULootLockerServerCharacterRequest.html", null ],
      [ "ULootLockerServerConfig", "classULootLockerServerConfig.html", null ],
      [ "ULootLockerServerConnectedAccountsRequest", "classULootLockerServerConnectedAccountsRequest.html", null ],
      [ "ULootLockerServerCurrencyRequest", "classULootLockerServerCurrencyRequest.html", null ],
      [ "ULootLockerServerDropTableRequest", "classULootLockerServerDropTableRequest.html", null ],
      [ "ULootLockerServerEnumUtils", "classULootLockerServerEnumUtils.html", null ],
      [ "ULootLockerServerForCpp", "classULootLockerServerForCpp.html", null ],
      [ "ULootLockerServerFriendsRequest", "classULootLockerServerFriendsRequest.html", null ],
      [ "ULootLockerServerGameProgressionRequest", "classULootLockerServerGameProgressionRequest.html", null ],
      [ "ULootLockerServerHeroRequest", "classULootLockerServerHeroRequest.html", null ],
      [ "ULootLockerServerInstanceProgressionRequest", "classULootLockerServerInstanceProgressionRequest.html", null ],
      [ "ULootLockerServerLeaderboardArchiveRequestHandler", "classULootLockerServerLeaderboardArchiveRequestHandler.html", null ],
      [ "ULootLockerServerLeaderboardRequest", "classULootLockerServerLeaderboardRequest.html", null ],
      [ "ULootLockerServerMetadataRequest", "classULootLockerServerMetadataRequest.html", null ],
      [ "ULootLockerServerNotificationsRequest", "classULootLockerServerNotificationsRequest.html", null ],
      [ "ULootLockerServerOAuthRequest", "classULootLockerServerOAuthRequest.html", null ],
      [ "ULootLockerServerPlayerFileRequest", "classULootLockerServerPlayerFileRequest.html", null ],
      [ "ULootLockerServerPlayerInventoryRequest", "classULootLockerServerPlayerInventoryRequest.html", null ],
      [ "ULootLockerServerPlayerProgressionRequest", "classULootLockerServerPlayerProgressionRequest.html", null ],
      [ "ULootLockerServerPlayerRequest", "classULootLockerServerPlayerRequest.html", null ],
      [ "ULootLockerServerStorageRequest", "classULootLockerServerStorageRequest.html", null ],
      [ "ULootLockerServerTriggerRequest", "classULootLockerServerTriggerRequest.html", null ]
    ] ]
];