var topics =
[
    [ "Initialization", "group__Init.html", "group__Init" ],
    [ "Authentication", "group__Authentication.html", "group__Authentication" ],
    [ "Token Exchange", "group__TokenExchange.html", "group__TokenExchange" ],
    [ "Player", "group__Player.html", "group__Player" ],
    [ "Player Files", "group__PlayerFiles.html", "group__PlayerFiles" ],
    [ "Player Storage", "group__PlayerStorage.html", "group__PlayerStorage" ],
    [ "Friends", "group__Friends.html", "group__Friends" ],
    [ "Connected Accounts", "group__ConnectedAccounts.html", "group__ConnectedAccounts" ],
    [ "Hero", "group__Hero.html", "group__Hero" ],
    [ "Characters", "group__Characters.html", "group__Characters" ],
    [ "Currency", "group__Currency.html", "group__Currency" ],
    [ "Balances", "group__Balances.html", "group__Balances" ],
    [ "Drop Tables", "group__DropTables.html", "group__DropTables" ],
    [ "Assets", "group__Assets.html", "group__Assets" ],
    [ "Asset Instances", "group__AssetInstance.html", "group__AssetInstance" ],
    [ "Player Progressions", "group__PlayerProgressions.html", "group__PlayerProgressions" ],
    [ "Character Progressions", "group__CharacterProgressions.html", "group__CharacterProgressions" ],
    [ "Asset Instance Progressions", "group__AssetInstanceProgressions.html", "group__AssetInstanceProgressions" ],
    [ "Progressions", "group__Progressions.html", "group__Progressions" ],
    [ "Leaderboards", "group__Leaderboard.html", "group__Leaderboard" ],
    [ "Triggers", "group__Triggers.html", "group__Triggers" ],
    [ "Metadata", "group__Metadata.html", "group__Metadata" ],
    [ "Notifications", "group__Notifications.html", "group__Notifications" ],
    [ "Catalogs", "group__Catalogs.html", "group__Catalogs" ]
];